### ISSUE TITLE
Plugin activation

### ISSUE THREAD

**Issue by rsd-raul** [mutual-of-enumclaw/serverless-plugin-local-env#1]
Hi Nikody, 

I just faced this exact problem and saw your post referencing this plugin, which is exactly what I'm looking for, as I don't mind deploying the full stack to use its resources.

The thing is I'm running 1.63.0 (and previously tried with 1.59.)3, but haven't managed to make the plugin work at all, apart from the environment vars behaving as usual, what gave it away was the fact that it's not generating the invoke.cache.json under .serverless.

Also tried packaging and deploying the sample, packaging doesn't generate the cache, deploying fails as I don't have access to the secret manager resource needed :S

Let me know if the sample still works for you, or if there is anything I'm missing at all.

Regards

**Comment by nkeating-mutualofenumclaw** [comment]
Looks like there was a syntax error, which is now fixed as of "e4c2d6a"
